name: WalletService Postman Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-wallet-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Run Postman Tests (WalletService)
        run: npm run test:wallet

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-results
          path: newman
